classDiagram
    Basket --> Item
    Item --> Bagel
    class Bagel
    Bagel : +string name
    Bagel : +number price
    class Item
    Item : +number id
    Item : +number quantity
    Item : +Bagel item
    class Basket
    Basket : +Bagel[] items
    Basket : +number currentID
    Basket : +number size
    Basket : +addItem(Bagel item) Bagel | string
    Basket : +removeItem(number id) Bagel | string